# Generated by Django 6.0 on 2025-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
    ]
