# Generated by Django 6.0 on 2025-12-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customusermodel_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_admin',
        ),
    ]
